[workspace]
authors = [
  "jessica-moylan <jessicamoylan10@gmail.com>",
  "Thomas Hopkins <thopkins1@bnl.gov>",
]
channels = ["conda-forge"]
name = "blop"
platforms = ["linux-64", "osx-arm64"]
version = "1.0.0b1"

[dependencies]
python = ">=3.11.0,<3.14"

[feature.dev.dependencies]

[feature.dev.pypi-dependencies]
blop = { path = ".", editable = true, extras = ["dev"] }
blop-sim = { path = "sim", editable = true }

# CPU-only variant of dev feature
[feature.dev-cpu.dependencies]

[feature.dev-cpu.pypi-dependencies]
blop = { path = ".", editable = true, extras = ["dev", "cpu"] }
blop-sim = { path = "sim", editable = true }

[feature.dev-cpu.tasks]
check = "pre-commit run --all-files"
tests = "pytest src/blop/tests"

[feature.docs.dependencies]
graphviz = ">=14.1.2,<15"

[feature.docs.pypi-dependencies]
blop-sim = { path = "sim", editable = true }
numpydoc = "*"
sphinx-copybutton = "*"
sphinxcontrib-mermaid = "*"
myst-nb = "*"
furo = "*"
jupytext = "*"
pydata-sphinx-theme = "*"
tiled = { version = ">=0.2.0", extras = ["all"] }
bluesky-tiled-plugins = "*"
ophyd-async = "*"
opencv-python = "*"

[feature.py311.dependencies]
python = "3.11.*"

[feature.py312.dependencies]
python = "3.12.*"

[feature.py313.dependencies]
python = "3.13.*"

[feature.docs.tasks]
start-queueserver = "docker compose -f docs/source/tutorials/queueserver/docker-compose.yml up -d --build --wait"
stop-queueserver = "docker compose -f docs/source/tutorials/queueserver/docker-compose.yml down"
build-docs = { cmd = "make -C docs/ html; EXIT_CODE=$?; docker compose -f docs/source/tutorials/queueserver/docker-compose.yml down; exit $EXIT_CODE", depends-on = [
  "start-queueserver",
  "doc-tests",
] }
clean-docs = "make -C docs/ clean"
build-docs-no-exec = { cmd = "BLOP_DOCS_NO_EXEC=1 make -C docs/ html" }
doc-tests = { cmd = "make -C docs/ test", depends-on = ["start-queueserver"] }
convert-tutorials-to-ipynb = "jupytext --to notebook docs/source/tutorials/*.md"

[environments]
dev = ["dev"]
dev-cpu = ["dev-cpu"]
docs = ["dev-cpu", "docs"]
py311-cpu = ["dev-cpu", "py311"]
py312-cpu = ["dev-cpu", "py312"]
py313-cpu = ["dev-cpu", "py313"]
